# This workflow will build, test, and publish a .NET project to NuGet
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET CI/CD

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Setup .NET SDK
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build project
    - name: Build
      run: dotnet build --no-restore

    # Run unit tests
    - name: Test
      run: dotnet test --no-build --verbosity normal

    # Publish NuGet package (only for main branch)
    - name: Publish to NuGet
      if: github.ref == 'refs/heads/main'  # Only publish on main branch
      run: dotnet pack --no-build --configuration Release -o ./nupkg
      env:
        NUGET_API_KEY: ${{ secrets.NUGET_PACKAGE_TOKEN }}

    # Push the package to NuGet
    - name: Push to NuGet
      if: github.ref == 'refs/heads/main'  # Only publish on main branch
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_PACKAGE_TOKEN }} --source https://api.nuget.org/v3/index.json
